# Setup
title:        Empirical Security
tagline:      Observations and experiences of an Information Security professional.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Empirical Security
  url:        http://empiricalsecurity.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
